import type { Metadata } from "next";
import { Noto_Sans, Titillium_Web } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import {CommandBar} from "@/components/ui/CommandBar/CommandBar";
import Header from "@/components/common/Header";

const titilliumWeb = Titillium_Web({
  subsets: ["latin"],
  weight: ["300"],
  display: "swap",
  variable: "--font-titillium",
});
const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto",
});
const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.woff2",
  display: "swap",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-950 text-white ${satoshi.variable} ${notoSans.variable}`}>
        <Header />
        {children}
        <CommandBar />  
      </body>
    </html>
  );
}