import type { Metadata } from "next";
import { Noto_Sans, Titillium_Web } from "next/font/google";
import "./globals.css";
import {CommandBar} from "@/components/ui/CommandBar/CommandBar";

const titilliumWeb = Titillium_Web({
  subsets: ["latin"],
  weight: ["300"],
  display: "swap",
  variable: "--font-titillium",
});
const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${titilliumWeb.variable} ${notoSans.variable}`}>
        {children}
        <CommandBar />  
      </body>
    </html>
  );
}
